---

- file: path="{{pre_check_tmp}}/res1.log" state=absent
  
- file: path="{{pre_check_tmp}}/res.log" state=absent
  
- file: path="{{pre_check_tmp}}/res2.log" state=absent

- file: path="{{pre_check_tmp}}/res1.log" state=touch
  
- file: path="{{pre_check_tmp}}/res.log" state=touch
  
- file: path="{{pre_check_tmp}}/res2.log" state=touch


- shell: "if [[ $(lsblk /dev/sd{{item}} | wc -l) = 2 ]]; then lsblk /dev/sd{{item}} | grep G ; fi" 
  ignore_errors: true
  register: x
  with_items: "{{letters}}"
    
- shell: echo {{item.stdout}} >> {{pre_check_tmp}}/res1.log          
  when: item.stdout is defined and item.stdout!=""
  with_items: "{{x.results}}"

- set_fact: gotit=true          
  when: item.stdout is defined and item.stdout!=""
  with_items: "{{x.results}}"
    
- block: 
     - shell: "echo '{{inventory_hostname}} ,' > {{pre_check_tmp}}/res.log"        
             
     - shell: awk '{ print "disk1="$1 " " $4 " " }' {{pre_check_tmp}}/res1.log >> {{pre_check_tmp}}/res.log
     
     - shell: ls -lad /opt/tools/dynatrace/ >> {{pre_check_tmp}}/res2.log
       become: true
       ignore_errors: true
     
     - shell:  awk '{ print "," $9 }' {{pre_check_tmp}}/res2.log >> {{pre_check_tmp}}/res.log
     
     - shell: tr -s '\n' ' ' <{{pre_check_tmp}}/res.log >> {{pre_check_logs}}
  when: gotit
