---


- shell: echo  >> {{pre_check_logs}}
- shell: "echo 'Check disk of {{inventory_hostname}} start *************' >> {{pre_check_logs}}"
         
         
- name: precheck
  shell: |
         echo 'Dynatrace folder exist?:' >> {{pre_check_logs}} 2>&1
         ls -la /opt/tools/dynatrace >> {{pre_check_logs}} 2>&1
         echo 'Dynatrace running?:' >> {{pre_check_logs}} 2>&1
         ps -ef | grep oneagent | wc -l  >> {{pre_check_logs}} 2>&1
         echo 'Free memory:' >> {{pre_check_logs}} 2>&1
         free -m|grep 'Mem:' | awk '{print $4}' >> {{pre_check_logs}} 2>&1                    
  become: true
  ignore_errors: true
  
- shell: "echo 'Check disk of {{inventory_hostname}} end *************' >> {{pre_check_logs}}"

