---

- shell: echo  >> {{pre_check_logs}}
- shell: echo 'Remove VG of {{inventory_hostname}} *************' >> {{pre_check_logs}}


- name: vg remove
  lvg:
    vg: "{{ vgname }}"
    state: absent
  ignore_errors: true
  register: x  
  
- shell: "echo '***Success*** remove VG {{ vgname }}!'  >> {{pre_check_logs}}"
  when: x is not failed    

- block:   
     - shell: |
              echo '***Error*** remove VG {{ vgname }}!'  >> {{pre_check_logs}}
              echo '{{x.msg}}' >> {{pre_check_logs}}
     - set_fact: contr=false
  when: x is failed

- shell: echo  >> {{pre_check_logs}}