---

contp: true

email_to: # survey  
email_subject: "Query Disk output on {{ ansible_fqdn }}"
email_body: "See the attachment email.txt to see the results of this run."     

gotit:
partition: 1
raw_prefix: sd
disk_size_2check: 10

# excluded the a for a might the os like sda
letters:
   - b
   - c
   - d
   - e
   - f
   - g
   - h 
   - i 
   - j 
   - k

# numbers should be the same as the letters   
numbers:
  - 0
  - 1
  - 2
  - 3 
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9  

dynatrace_ip:   
  - 127.0.0.1 
