---

- shell: echo  >> {{pre_check_logs}}
- shell: "echo 'Create FS of {{inventory_hostname}} *************' >> {{pre_check_logs}}"

- shell: "grep -m1 ' xfs ' /etc/fstab"
  register: x
  ignore_errors: true

- set_fact: fst="xfs"
  when: x.stdout|regex_search('xfs')
  
- shell: "grep -m1 ' ext3 ' /etc/fstab"
  register: x
  ignore_errors: true  

- set_fact: fst="ext3"
  when: x.stdout|regex_search('ext3')
  
- name: create fs
  filesystem:
    fstype: "{{ fst }}"
    dev: "{{ src }}"
    force: "{{ force }}"
  register: x
  ignore_errors: true
     
  
- shell: "echo '***Success*** creation fs of /dev/{{ vgname }}/{{ lvname }} type={{fst}}!' >> {{pre_check_logs}}"
  when: x is not failed
  
- block:
     - shell: |
              echo '***Error*** creation fs of /dev/{{ vgname }}/{{ lvname }}!' >> {{pre_check_logs}}
              echo '{{x.msg}}' >> {{pre_check_logs}}
     - set_fact: contx=false        
  when: x is failed
  
- shell: echo  >> {{pre_check_logs}}  
