---

- shell: echo  >> {{pre_check_logs}}
- shell: echo 'Create DEV of {{inventory_hostname}} *************' >> {{pre_check_logs}}

- set_fact: pvname='mapper/{{disk1}}'
  when: disk1|regex_search('mpath')
  
- set_fact: pvlist='/dev/{{pvname}}{{partition}}'
  when: disk1|regex_search('mpath')  

# for failsafe
- shell: fdisk -l /dev/{{pvname}}
  register: x

- block:  
     - shell: echo '***Error*** other PARTITION found {{pvname}}[x]!' >> {{pre_check_logs}}
     - set_fact: contx=false             
     - meta: end_play
  when: x.stdout | regex_search('/dev/{{ pvname }}1') or x.stdout | regex_search('/dev/{{ pvname }}2') or x.stdout | regex_search('/dev/{{ pvname }}3') or x.stdout | regex_search('/dev/{{ pvname }}4')           
            
- name: Create the DEV 1 type P
  shell: (echo n; echo {{ type }}; echo {{ partition }}; echo ; echo +{{ disksize }}; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: type == "p" and disksize is defined
  ignore_errors: yes
  register: x  
    
- name: Create the DEV 1 type P use all
  shell: (echo n; echo {{ type }}; echo {{ partition }}; echo ; echo ; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: type == "p" and disksize is not defined
  ignore_errors: yes
  register: x  
  
- name: Create the DEV l type L
  shell: (echo n; echo l; echo ; echo +{{ disksize }}; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: type == "l" and disksize is defined
  ignore_errors: yes
  register: x
  
- name: Create the DEV l type L use all
  shell: (echo n; echo l; echo ; echo ; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: type == "l" and disksize is not defined  
  ignore_errors: yes
  register: x  

- shell: "echo '***Success*** creation of DEV {{pvlist}}' >> {{pre_check_logs}}"
  when: x is not failed
  
- block:  
     - shell: |
              echo '***Error*** creation of DEV {{pvlist}}' >> {{pre_check_logs}}
              echo {{x.msg}} >> {{pre_check_logs}}
     - set_fact: contx=false
     - meta: end_play
  when: x is failed

  
- name: Change the type to LVM for DEV 1
  shell: (echo t; echo {{ ptype }}; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: partition == "1"
  ignore_errors: yes
  register: x

- name: Change the type to LVM for DEV >1
  shell: (echo t; echo {{ partition }}; echo {{ ptype }}; echo w) | fdisk /dev/{{ pvname }}
  ignore_errors: true
  when: not(partition == "1")
  ignore_errors: yes
  register: x

- shell: "echo '***Success*** change type of DEV {{pvlist}} to {{ptype}}!' >> {{pre_check_logs}}"
  when: x is not failed
  
- block:  
     - shell: |
              echo '***Error*** change type of DEV {{pvlist}} to {{ptype}}!' >> {{pre_check_logs}}
              echo '{{x.msg}}' >> {{pre_check_logs}}
     - set_fact: contx=false
  when: x is failed
  
- block:
  
   - shell: partprobe
     register: x
   
   - shell: "echo '***Success*** run of partprobe!' >> {{pre_check_logs}}"
     when: x is not failed 
     
   - block:  
        - shell: |
                 echo '***Error*** run of partprobe!' >> {{pre_check_logs}}
                 echo '{{x.msg}}' >> {{pre_check_logs}}
        - set_fact: contx=false
     when: x is failed
  
  when: disk1|regex_search('mpath')

- shell: echo  >> {{pre_check_logs}}
