---

- shell: echo  >> {{pre_check_logs}}
- shell: "echo 'Create LV of {{inventory_hostname}} *************' >> {{pre_check_logs}}"
  
- set_fact: pvlist='/dev/mapper/{{disk1}}{{partition}}'
  when: disk1|regex_search('mpath')  
  
- name: lvcreate
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname }}"
    size: "{{ size }}"
    pvs: "{{ pvlist }}"
    force: "{{ force }}"
    active: "{{ active }}"  
  register: x
  ignore_errors: true
  
- shell: "echo '***Success*** creation of LV {{vgname}}' >> {{pre_check_logs}}"
  when: x is not failed
  
- block:  
     - shell: |
              echo '***Error*** creation of LV {{vgname}}' >> {{pre_check_logs}}
              echo '{{x.msg}}' >> {{pre_check_logs}}
     - set_fact: contx=false
  when: x is failed
    

- shell: echo  >> {{pre_check_logs}}
