---


- shell: echo  >> {{pre_check_logs}}
- shell: "echo 'Mount FS of {{inventory_hostname}} *************' >> {{pre_check_logs}}"

- set_fact: src='/dev/mapper/{{vgname}}-{{lvname}}'
  when: disk1|regex_search('mpath')

- name: mount fs
  mount:
    path: "{{ fsname }}"
    src: "{{ src }}"
    fstype: "{{ fst }}"
    state: "mounted"
  ignore_errors: true
  register: x
 
 
- shell: "echo '***Success*** mount of {{ fsname }}!' >> {{pre_check_logs}}"
  when: x is not failed 
  
- shell: |
         echo ***Error*** mount of {{ fsname }}!!  >> {{pre_check_logs}}
         echo '{{x.msg}}'  >> {{pre_check_logs}}
  when: x is failed
 
- shell: echo  >> {{pre_check_logs}}    
