---

- shell: cat > ./email.txt
  delegate_to: localhost # tower-server
  run_once: true

- name: Fetching logs to Tower
  fetch:
    src: "{{pre_check_logs}}"
    dest: "./{{pre_check_file}}"
    flat: yes
    
- shell: cat ./{{pre_check_file}} >> ./email.txt
  delegate_to: localhost # tower-server
       
- name: Send email to group.
  mail:
    subject: "{{email_subject}}"
    host: 'mail.yahoo.com'
    port: 25
    body: '{{email_body}}'
    from: '{{email_group}}'
    to: '{{email_to}}'
    attach: './email.txt'
  delegate_to: localhost # tower-server
  run_once: true  
  ignore_errors: true
  when: send_mail=='TRUE'

- debug:
    msg: 'Pre-check logs {{pre_check_logs}} sent email to SA/DB.'
  run_once: true   
  
